# Generated by Django 6.0.5 on 2026-05-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
